### ISSUE TITLE
go-iscsi-helper: command failed: fork/exec /usr/sbin/tgtd: exec format error

### ISSUE THREAD

**Issue by ternes3** [longhorn/go-iscsi-helper#40]
I am running an ubuntu 20.04.3 host with RKE2 on top. Current version of rancher := 2.6.0 and longhorn := 1.1.2 installed via Rancher Catalog Apps. 

It is not possible for me to attach a volume to an pod. Following warnings I see inside of the logs. 

```time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Starting with replicas [\\\"tcp://10.42.0.118:10000\\\"]\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Connecting to remote: 10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Opening: 10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Adding backend: tcp://10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Start monitoring tcp://10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Get backend tcp://10.42.0.118:10000 revision counter 0\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"device pvc-abf2502c-bd3a-41cf-88be-f25743c2f742: SCSI device /dev/longhorn/pvc-abf2502c-bd3a-41cf-88be-f25743c2f742 shutdown\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: go-iscsi-helper: command failed: fork/exec /usr/sbin/tgtd: exec format error"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: panic: fork/exec /usr/sbin/tgtd: exec format error"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: "
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: goroutine 101 [running]:"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: github.com/longhorn/go-iscsi-helper/iscsi.startDaemon(0xc0000100c8, 0x100)"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: \t/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go:201 +0x449"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: created by github.com/longhorn/go-iscsi-helper/iscsi.StartDaemon"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: \t/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go:165 +0xad"```

Any Idea?

**Comment by jenting** [comment]
Close this issue, use the https://github.com/longhorn/longhorn/issues/3043 to track it.
